### PR TITLE
Reimplement `wac-parser` on `wac-graph`.

### LINKED ISSUE #37: Encode local names in a composition to a `names` section
In anticipation of decoding a wasm binary to a WAC source file, we should be encoding local names in a `names` custom section in the resulting composition, with an option to skip emitting the section if a faithful decoding is not required.

### LINKED ISSUE #76: `wac-parser` not checking for type declaration conflicting with previous export
The following wac:

```wac
package test:comp;

let foo = new foo:bar {};

export foo as i;

interface i {
}
```

causes a panic in `wac-parser`:

```
thread 'main' panicked at crates/wac-parser/src/resolution/ast.rs:355:9:
assertion failed: prev.is_none()
```

This is because `wac-parser` is not emitting an error for the type declaration conflicting with the previous export.

### LINKED ISSUE #78: `wac-graph`: defined types need dependency edges to other defined types
Currently `CompositionGraph::define_type` allows for exporting a named type from the composition.

However, the node it creates in the graph has no dependency edges on other defined types that might be referenced from the type definition.

The result is that the toposort performed when the graph is encoded does not properly order the types such that they are in correct topological order (although the ordering is a stable one).

The fix is to add a "depends on" edge from the node to any defined type referenced from the type being defined.

### LINKED ISSUE #79: `wac-graph`: `CompositionGraph` should debug to a DOT format
Add a `Debug` implementation for `CompositionGraph` that renders to a DOT representation.

### PR DESCRIPTION
**Pull request by peterhuene**
This PR is a complete reimplementation of `wac-parser`'s resolution to be based on `wac-graph`.

It also contains an overhaul of the `wac-graph` API to facilitate its use from `wac-parser`:

* Reimplements `CompositionGraph` on top of `petgraph::StableDiGraph`, which eliminates needing to keep track of nodes internally to `CompositionGraph`.
* Packages now populate their type information into the graph's types collection rather than having their own collections.
* Splits the `Error` enum into discrete error types for each graph operation; this allows the AST resolver to properly attach span information to errors.
* Add type dependency edges for defined types, ensuring topological ordering.
* Fix encoding of defined type aliases so that each encoded alias refers to the export index of the previously encoded type.
* Added a debug formatter for `CompositionGraph` that outputs a DOT representation (used in resolution tests as well).
* Graph encoding now includes an optional producers custom section.
* Fixed toposort to be in ascending node index order for independent nodes.

The subtype checker implementation was reverted to the previous implementation, where `invert` and `revert` are called at specific points to change the type of check being performed; the newer implementation did not give the correct "expected, found" error messages for AST resolution.

`wac resolve` now outputs a DOT representation of the resolved composition graph instead of JSON.

A names custom section is now included in the output of an encoded WAC document.

Most of the deleted code comes from code that has already moved into `wac-types` and `wac-graph`.

Closes #79.
Fixes #78.
Fixes #76.
Closes #37.

### CODE REVIEW

**Comment by peterhuene** [comment]
When this and a fix for #81 lands, I plan on adding a publish script to CI and creating a `0.1.0` tag to publish to crates.

File: src/commands/encode.rs [hunk 1]
```diff
@@ -64,7 +64,7 @@ pub struct EncodeCommand {
     #[clap(long, value_name = "URL")]
     pub registry: Option<String>,
 
-    /// The path to the composition file.
+    /// The path to the source file.
```
Comment (rylev) [inline src/commands/encode.rs:67]: Perhaps say that this should be the `.wac` file?

**Review by rylev — CHANGES_REQUESTED** [review]
I'm seeing a stack overflow when running this against my own project. It seems that for some reason, a particular interface that we're merging into the types collection has an export (a resource) that depends on the interface itself - specifically the resource alias owner is the interface being merged. This causes an infinite loop since we've not yet registered this interface as being remapped.

File: crates/wac-types/src/aggregator.rs [hunk 2]
```diff
@@ -243,32 +226,22 @@ impl TypeAggregator {
...
+                    .is_subtype(*source_kind, types, target_kind, &self.types)
                     .with_context(|| format!("mismatched type for export `{name}`"))?;
             }
 
             let remapped = self.remap_item_kind(types, *source_kind, checker)?;
             self.types[existing].imports.insert(name.clone(), remapped);
         }
 
+        checker.revert();
+
```
Comment (rylev) [inline crates/wac-types/src/aggregator.rs:238]: Can you explain why this stateful approach is better than passing whether the check is covariant or contravariant as an argument?

File: crates/wac-types/src/package.rs [hunk 3]
```diff
@@ -154,23 +164,34 @@ pub struct Package {
...
 
     /// Creates a new package from the given bytes.
+    ///
+    /// The package will populate its types into the provided type collection.
     pub fn from_bytes(
         name: &str,
         version: Option<&Version>,
-        bytes: impl Into<Arc<Vec<u8>>>,
+        bytes: impl Into<Vec<u8>>,
+        types: &mut Types,
```
Comment (rylev) [inline crates/wac-types/src/package.rs:194]: Even though it's not necessary... I wonder if the `wac-graph` crate should define a new type for `Package` that wraps this one and ensures the `Types` provided comes from the graph...

File: crates/wac-graph/src/graph.rs [hunk 4]
```diff
@@ -274,39 +285,36 @@ impl RegisteredPackage {
...
     /// The optional name to associate with the node.
     ///
     /// When the graph is encoded, node names are recorded in a `names` custom section.
-    name: Option<String>,
+    pub name: Option<String>,
     /// The name to use for exporting the node.
-    export: Option<String>,
-    /// The aliased nodes from this node.
-    aliases: HashMap<String, NodeId>,
+    pub export: Option<String>,
```
[the remark this answers is not in the document]
Comment (peterhuene) [reply crates/wac-graph/src/graph.rs:307]: Certainly can't hurt. I'll fix it.

File: crates/wac-types/src/package.rs (hunk 3 above)
Comment (peterhuene) [reply crates/wac-types/src/package.rs:194]: For my understanding, could you explain a bit more what this might look like?

File: crates/wac-types/src/aggregator.rs (hunk 2 above)
Comment (peterhuene) [reply crates/wac-types/src/aggregator.rs:238]: The current check doesn't properly account for the inversion that takes place when these things nest; it was always forcing the check at each recursion point to a particular kind of check when rather it should invert the current relationships.

For example, if we're type checking an instance import of a world, the type check that's performed on the instance's exports should be *contravariant*, but because the subtype checks were passing *covariant*, the error messages in some of the test baselines came out backwards with regards to what was expected and what was found.

The current check was just one of those "refactor and attempt to improve, but forget why it was done that way originally" type of things.

File: crates/wac-types/src/component.rs [hunk 5]
```diff
@@ -684,9 +789,9 @@ impl fmt::Display for FuncKind {
 #[cfg_attr(feature = "serde", derive(serde::Serialize))]
 #[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
 pub struct ResourceAlias {
-    /// The owning interface for the resource.
+    /// The foreign owning interface for the resource.
     ///
-    /// This may be `None` if the resource is owned by a world.
+    /// This may be `None` if the resource does not have a foreign interface owner.
```
Comment (rylev) [inline crates/wac-types/src/component.rs:794]: I'm sure to forget about when there isn't a foreign owner so it'd be nice to document that.

```suggestion
    /// This may be `None` if the resource does not have a foreign interface owner such as in a world or when aliasing within the same interface. 
```

**Review by rylev — APPROVED** [review]

File: crates/wac-types/src/package.rs (hunk 3 above)
Comment (rylev) [reply crates/wac-types/src/package.rs:194]:
```rust
struct Package(wac_types::Package);

impl Package {
   pub fn from_bytes(
        name: &str,
        version: Option<&Version>,
        bytes: impl Into<Vec<u8>>,
       graph: &mut CompositionGraph
 ) -> Result<Self> {
  Self(wac_types::Package::from_bytes(name, version, bytes, graph.types_mut())
}
```

This is probably overkill - I'm just worried about people being confused about how to supply the types collection.
